services:
  agui-frontend:
    image: agui-frontend:latest
    network_mode: host
    restart: unless-stopped
    container_name: agui-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
